// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models;

public partial class ApplicationRole
{
    public int id { get; set; }

    public int applicationId { get; set; }

    public string applicationRoleName { get; set; }

    public int? parentId { get; set; }

    public virtual ICollection<ApplicationRole> Inverseparent { get; set; } = new List<ApplicationRole>();

    public virtual Application application { get; set; }

    public virtual ApplicationRole parent { get; set; }

    public virtual ICollection<Person> emails { get; set; } = new List<Person>();
}