// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models;

public partial class Campus
{
    public int id { get; set; }

    public string campusName { get; set; }

    public virtual ICollection<Degree> Degrees { get; set; } = new List<Degree>();

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<School> Schools { get; set; } = new List<School>();
}