// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models;

public partial class OrganizationType
{
    public int id { get; set; }

    public string organizationTypeName { get; set; }

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();
}