// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models;

public partial class Organization
{
    public string email { get; set; }

    public int? degreeId { get; set; }

    public string organizationPassword { get; set; }

    public string organizationName { get; set; }

    public int organizationTypeId { get; set; }

    public bool isCouncil { get; set; }

    public virtual Degree degree { get; set; }

    public virtual OrganizationType organizationType { get; set; }
}