// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models;

public partial class Student
{
    public int id { get; set; }

    public string email { get; set; }

    public int degreeId { get; set; }

    public bool isExemptFromPrintingCosts { get; set; }

    public virtual Degree degree { get; set; }

    public virtual Person emailNavigation { get; set; }
}