// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeApplication;
//
//    var application = Application.FromJson(jsonString);

namespace LayoutTemplateWebApp.Models.QuickTypeApplication
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Application
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("applicationName")]
        public string ApplicationName { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("applicationRoles")]
        public object[] ApplicationRoles { get; set; }
    }

    public partial class Application
    {
        public static Application FromJson(string json) => JsonConvert.DeserializeObject<Application>(json, QuickTypeApplication.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Application self) => JsonConvert.SerializeObject(self, QuickTypeApplication.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
