// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeDegree;
//
//    var deegreeList = DeegreeList.FromJson(jsonString);

namespace LayoutTemplateWebApp.Models.QuickTypeDegree
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DeegreeList
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("degreeName")]
        public string DegreeName { get; set; }

        [JsonProperty("campusId")]
        public long CampusId { get; set; }

        [JsonProperty("organizations")]
        public object[] Organizations { get; set; }

        [JsonProperty("students")]
        public object[] Students { get; set; }

        [JsonProperty("campus")]
        public object Campus { get; set; }
    }

    public partial class DeegreeList
    {
        public static DeegreeList[] FromJson(string json) => JsonConvert.DeserializeObject<DeegreeList[]>(json, QuickTypeDegree.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DeegreeList[] self) => JsonConvert.SerializeObject(self, QuickTypeDegree.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
