// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models
{
    public partial class Application
    {
        public Application()
        {
            ApplicationRoles = new HashSet<ApplicationRole>();
        }

        public int id { get; set; }
        public string applicationName { get; set; }
        public string description { get; set; }

        public virtual ICollection<ApplicationRole> ApplicationRoles { get; set; }
    }
}