// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models
{
    public partial class Campus
    {
        public Campus()
        {
            Degrees = new HashSet<Degree>();
            Departments = new HashSet<Department>();
            Schools = new HashSet<School>();
        }

        public int id { get; set; }
        public string campusName { get; set; }

        public virtual ICollection<Degree> Degrees { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<School> Schools { get; set; }
    }
}