// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models
{
    public partial class Degree
    {
        public Degree()
        {
            Organizations = new HashSet<Organization>();
            Students = new HashSet<Student>();
        }

        public int id { get; set; }
        public string degreeName { get; set; }
        public int campusId { get; set; }

        public virtual Campus campus { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}