// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_Tec_Web_API.Models
{
    public partial class Person
    {
        public Person()
        {
            applicationRoles = new HashSet<ApplicationRole>();
            departments = new HashSet<Department>();
            schools = new HashSet<School>();
        }

        public string email { get; set; }
        public string personPassword { get; set; }
        public int id { get; set; }
        public string personName { get; set; }
        public string firstLastName { get; set; }
        public string secondLastName { get; set; }
        public int debt { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }

        public virtual ICollection<ApplicationRole> applicationRoles { get; set; }
        public virtual ICollection<Department> departments { get; set; }
        public virtual ICollection<School> schools { get; set; }
    }
}